# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thex', '0002_auto_20170130_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hostgalaxy',
            name='redshift',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transient',
            name='transient_subtype',
            field=models.CharField(default='AT', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostgalaxy',
            name='dec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hostgalaxy',
            name='ra',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transient',
            name='dec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transient',
            name='ra',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transient',
            name='transient_type',
            field=models.CharField(choices=[('SN', 'Supernova'), ('GRB', 'Gamma Ray Burst'), ('TDE', 'Tidal Disruption Event'), ('Nova', 'Nova'), ('AT', 'Astronomical Transient')], default='AT', max_length=10),
        ),
        migrations.AddField(
            model_name='hostname',
            name='galaxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thex.HostGalaxy'),
        ),
    ]
