# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thex', '0004_auto_20170201_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgalaxy',
            name='dec',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='hostgalaxy',
            name='ra',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='hostgalaxy',
            name='redshift',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='transient',
            name='dec',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='transient',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='thex.HostGalaxy'),
        ),
        migrations.AlterField(
            model_name='transient',
            name='peak_brightness',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='transient',
            name='ra',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='transient',
            name='transient_subtype',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
