# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thex', '0005_auto_20170203_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='discovery_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='transient',
            name='name',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transient',
            name='redshift',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hostgalaxy',
            name='dec',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hostgalaxy',
            name='ra',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hostgalaxy',
            name='redshift',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='galaxy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='thex.HostGalaxy'),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='transient',
            name='dec',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transient',
            name='host',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='thex.HostGalaxy'),
        ),
        migrations.AlterField(
            model_name='transient',
            name='peak_brightness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transient',
            name='ra',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transient',
            name='transient_subtype',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
